// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SEmOG8VZn1U2KXeKKF4ubFrnrhyTE6Y',
    appId: '1:482569997048:web:6aaeb50ef75610e153890d',
    messagingSenderId: '482569997048',
    projectId: 'warehouses-managment',
    authDomain: 'warehouses-managment.firebaseapp.com',
    storageBucket: 'warehouses-managment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBGiyOkRFc9R5OjjustiV3ra16r7LLSk',
    appId: '1:482569997048:android:e0795b9cee4cde9653890d',
    messagingSenderId: '482569997048',
    projectId: 'warehouses-managment',
    storageBucket: 'warehouses-managment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCczvBMxJIg12ZojyrxHlIfNfdob9DZ0',
    appId: '1:482569997048:ios:2b95fe8e934f97ab53890d',
    messagingSenderId: '482569997048',
    projectId: 'warehouses-managment',
    storageBucket: 'warehouses-managment.appspot.com',
    iosBundleId: 'com.example.mobileWarehouseManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCczvBMxJIg12ZojyrxHlIfNfdob9DZ0',
    appId: '1:482569997048:ios:2b95fe8e934f97ab53890d',
    messagingSenderId: '482569997048',
    projectId: 'warehouses-managment',
    storageBucket: 'warehouses-managment.appspot.com',
    iosBundleId: 'com.example.mobileWarehouseManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SEmOG8VZn1U2KXeKKF4ubFrnrhyTE6Y',
    appId: '1:482569997048:web:76dbb1f9cc142e9d53890d',
    messagingSenderId: '482569997048',
    projectId: 'warehouses-managment',
    authDomain: 'warehouses-managment.firebaseapp.com',
    storageBucket: 'warehouses-managment.appspot.com',
  );
}
